name: Release KAITO Plugin
env:
  NODE_VERSION: '22.X'
  RELEASE_TAR: 'headlamp-kaito-plugin-${{ github.event.inputs.releaseVersion }}.tar.gz'

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version (without v prefix)'
        required: true
        default: '0.0.0'

permissions: read-all

jobs:
  release:
    name: Release KAITO Plugin
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Update package.json version
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: package.json
          propertyPath: version
          value: '${{ github.event.inputs.releaseVersion }}'
          commitChange: false

      - name: Create Plugin Archive
        run: |
          mkdir -p headlamp-kaito-plugin
          cp -r dist/* headlamp-kaito-plugin/
          tar -czf ${{ env.RELEASE_TAR }} headlamp-kaito-plugin

      - name: Calculate SHA256 Checksum
        id: checksum
        run: echo "value=$(sha256sum ${{ env.RELEASE_TAR }} | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Get Current Date
        id: date
        run: echo "value=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Update artifacthub-pkg.yml
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: artifacthub-pkg.yml
          changes: |
            {
              "version": "${{ github.event.inputs.releaseVersion }}",
              "createdAt": "${{ steps.date.outputs.value }}",
              "annotations[\"headlamp/plugin/archive-url\"]": "https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.releaseVersion }}/${{ env.RELEASE_TAR }}",
              "annotations[\"headlamp/plugin/archive-checksum\"]": "SHA256:${{ steps.checksum.outputs.value }}"
            }
          commitChange: false

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Release ${{ github.event.inputs.releaseVersion }}
          add: |
            - artifacthub-pkg.yml
            - package.json

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          prerelease: true
          files: ${{ env.RELEASE_TAR }}
          token: ${{ github.token }}